name: Build and Upload Executable

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64' 

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Executable
        run: pyinstaller --paths "C:\Python311\Lib\site-packages" "app.py"

      - name: Zip Executable
        run: |
          7z a dist.zip dist

      - name: Upload Zip
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: dist.zip
